server:
  port: 8085 # notification-service

spring:
  application:
    name: notification-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: DEBUG
    org.spring.framework.web: DEBUG
    com.example.notification_service: DEBUG
