server:
  port: 8085 # notification-service

spring:
  application:
    name: notification-service
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
